---
# tasks file for openstack-ansible

- name: Installing mising packages
  apt:
     name: ['python-yaml']
     state: present

- name: Cloning the OpenStack-Ansible repository on the deployment node
  git:
    repo: https://opendev.org/openstack/openstack-ansible
    dest: /opt/openstack-ansible
    version: "{{ openstack_version }}"

- name: Bootstrapping ansible
  command: scripts/bootstrap-ansible.sh
  args:
    chdir: /opt/openstack-ansible

- name: Copying local configuration files to /etc/openstack_deploy in deployment node
  copy:
    src: openstack_deploy
    dest: /etc
  tags:
  - copyinguserconfig

- name: Copying etc/openstack_deploy into /etc in the deployment node
  command: cp -rn /opt/openstack-ansible/etc/openstack_deploy /etc
  tags:
  - copyinguserconfig
  register: copy_result

- name: Generaring random passphrases for the various OpenStack services
  command: python pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml
  args:
    chdir: /opt/openstack-ansible/scripts
  tags:
  - copyinguserconfig
