---

- name: Updating nodes in the environment and adding swap to them
  hosts: all
  become: yes
  roles:
  - common
  tags:
  - updatingnodes

# Setting up load balancer nodes

- name: Setting up load balancer nodes
  hosts: lb_nodes
  become: yes
  roles:
  - lb-nodes
  tags:
  - setup_lbnodes

# Setting up controller nodes

- name: Setting up controller nodes
  hosts: controller_nodes
  become: yes
  roles:
  - controller-nodes
  tags:
  - setup_controller_nodes

# Setting up compute nodes

- name: Setting up compute nodes
  hosts: compute_nodes
  become: yes
  roles:
  - compute-nodes
  tags:
  - set_compute_nodes

# Setting up network nodes

- name: Setting up network nodes
  hosts: network_nodes
  become: yes
  roles:
  - network-nodes
  tags:
  - setup_network_nodes

# Setting up cinder nodes

- name: Setting up cinder nodes
  hosts: cinder_nodes
  become: yes
  roles:
  - cinder-nodes
  tags:
  - setup_cinder_nodes

# Setting up storage nodes

- name: Setting up storage nodes (ceph)
  hosts: ceph_nodes
  become: yes
  roles:
  - ceph-nodes
  tags:
  - setup_ceph_nodes

- name: Setting up storage nodes (NFS)
  hosts: nfs_nodes
  become: yes
  roles:
  - nfs-nodes
  tags:
  - setup_nfs_nodes

- name: Setting up storage nodes (LVM)
  hosts: lvm_nodes
  become: yes
  roles:
  - lvm-nodes
  vars:
    pvs_devices: "/dev/vdb"
    cinder_vg: "cinder-volumes"
  tags:
  - setup_lvm_nodes

# Setting up logging nodes

- name: Setting up logging nodes
  hosts: logging_nodes
  become: yes
  roles:
  - logging-nodes
  tags:
  - setup_logging_nodes

# Setting up swift nodes

- name: Setting up swift nodes
  hosts: swift_nodes
  become: yes
  roles:
  - swift-nodes
  vars:
    swift_devices:
    - vdb
    - vdc
    - vdd
    - vde
    - vdf
  tags:
  - setup_swift_nodes

# Gatther used IP ddresses

- name: Gathering used IP addresses
  hosts: all
  tasks:
  - shell: "ip -o addr | grep -v inet6 | grep -vE 'eth0|127.0.0.1' | awk '{ print $4 }' | awk -F/ '{ printf \"%s,\", $1 }' | sed 's/,$//'"
    register: interfaces
  - debug:
      msg: "{{ interfaces.stdout }}"
    when: interfaces.rc == 0
  tags:
  - used_ips

- name: Cloning, preparing and bootstrapping OpenStack-Ansible
  hosts: deployment_nodes
  become: yes
  roles:
  - openstack-ansible
  tags:
  - openstackansiblesetup
  vars:
    openstack_version: stable/train

- name: Fetching the public key from the deployment node
  hosts: deployment_nodes
  become: yes
  tasks:
  - name: Fetching public key from deployment node
    fetch:
      dest: authorized_keys
      src: /root/.ssh/id_rsa.pub
      flat: yes
  tags:
  - copyingpublickey

- name: Copying SSH public key to the deploy nodes
  hosts: infrastructure_nodes
  become: yes
  tasks:
  - name: Making sure that the /root/.ssh directory exists
    file:
      mode: '0700'
      state: directory
      path: /root/.ssh
  - name: Copying public key to the authorized_keys file
    copy:
      src: authorized_keys
      mode: '0600'
      dest: /root/.ssh/authorized_keys
  tags:
  - copyingpublickey
