---

- name: Updating nodes in the environment and adding swap to them
  hosts: all
  become: yes
  roles:
  - common
  tags:
  - updatingnodes

- name: Setting up networking in controller nodes
  hosts: controller_nodes
  become: yes
  roles:
  - networking
  tags:
  - networking
  - networking_controllers
  vars:
    bridges:
    - br-mgmt
    - br-storage
    nodetype: controller

- name: Setting up networking in compute nodes
  hosts: compute_nodes
  become: yes
  roles:
  - networking
  tags:
  - networking
  - networking_computes
  vars:
    bridges:
    - br-mgmt
    - br-vxlan
    - br-storage
    - br-vlan
    nodetype: compute

- name: Setting up networking in network nodes
  hosts: network_nodes
  become: yes
  roles:
  - networking
  tags:
  - networking
  - networking_network
  vars:
    bridges:
    - br-mgmt
    - br-vxlan
    - br-vlan
    - br-ext
    nodetype: network

- name: Cloning, preparing and bootstrapping OpenStack-Ansible
  hosts: deployment_nodes
  become: yes
  roles:
  - openstack-ansible
  tags:
  - openstackansiblesetup

- name: Fetching the public key from the deployment node
  hosts: deployment_nodes
  become: yes
  tasks:
  - name: Fetching public key from deployment node
    fetch:
      dest: authorized_keys
      src: /root/.ssh/id_rsa.pub
      flat: yes
  tags:
  - copyingpublickey

- name: Copying SSH public key to the deploy nodes
  hosts: infrastructure_nodes
  become: yes
  tasks:
  - name: Making sure that the /root/.ssh directory exists
    file:
      mode: '0700'
      state: directory
      path: /root/.ssh
  - name: Copying public key to the authorized_keys file
    copy:
      src: authorized_keys
      mode: '0600'
      dest: /root/.ssh/authorized_keys
  tags:
  - copyingpublickey
