---
# tasks file for networking

- name: Making sure that brctl is installed
  apt:
    name: bridge-utils
    state: latest

- name: Creating networking configuration files
  template:
    src: "{{ nodetype }}-interfaces.j2"
    dest: /etc/network/interfaces
  tags:
  - networking_files_controllers

- name: Restarting networking.service so the new bridges come up
  systemd:
    state: restarted
    name: networking
