---
# tasks file for controller-nodes

- name: Setting up networking in controller nodes
  include_role:
    name: networking
  vars:
    nodetype: controller
  tags:
  - networking_openstack
  - networking_controller_nodes

- name: Set up the volume group for LXC containers
  lvg:
     vg: "{{ lxc_vg_name }}"
     pvs: "{{ lxc_pvs }}"
  when:
     - lxc_vg_name is defined
     - lxc_pvs is defined
